const CATALOG=[
 ['brawl30','Arena Regular','Win 30 ranked Brawls.','ranked win',30,'swords'],['brawl150','Arena Legend','Win 150 ranked Brawls.','ranked win',150,'crown'],
 ['mine100','Deep Delver','Collect 100 rubies from mines.','ruby mining',100,'pick'],['mine1000','Heart of the Mountain','Collect 1,000 rubies from mines.','ruby mining',1000,'gem',true],
 ['farm75','Green Fingers','Gather 75 farmhouse ingredients.','farm gathering',75,'leaf'],['cook25','Island Chef','Cook 25 pet meals.','meal cooked',25,'bowl'],['cook150','Grand Feast','Cook 150 pet meals.','meal cooked',150,'crown'],
 ['care40','Faithful Friend','Play with your pets 40 times.','pet play',40,'heart'],['journey20','Trail Keeper','Complete 20 pet journeys.','journey',20,'compass'],['journey100','Beyond the Horizon','Complete 100 pet journeys.','journey',100,'star',true],
 ['pack50','Curious Collector','Open 50 packs.','pack',50,'cards'],['ascend25','Rising Collection','Perform 25 ascensions.','ascension',25,'star'],['forge50','Forge Veteran','Convert cards 50 times.','conversion',50,'gem'],['amulet10','Master Jeweller','Craft 10 amulets.','amulet crafted',10,'gem'],
 ['time30','Keeper of Hours','Harvest 30 time boosts.','time bank work',30,'clock'],['vault60','Patient Banker','Earn 60 Footy through vault work.','vault work',60,'coin'],
 ['hall5','Growing Roots','Reach Town Hall level 5.','hall',5,'house'],['hall10','Island Architect','Reach Town Hall level 10.','hall',10,'crown'],['village30','A Thriving Village','Have 30 villagers.','villagers',30,'house'],['pets3','An Unlikely Family','Own all three companion species.','pets',3,'heart'],
 ['discover3','Off the Beaten Path','Discover all three island minigames.','discoveries',3,'compass',true]
].map(([id,name,description,metric,target,icon,secret=false])=>({id,name,description,metric,target,icon,secret}));
const count=v=>Math.max(0,Math.min(Number.MAX_SAFE_INTEGER,Math.floor(Number(v)||0)));
function metrics(u){return {...u.advancementStats,hall:require('./town-hall-progress').profile(u).level,villagers:require('./village-workforce').residents(u).length,pets:['pet:fox','pet:snail','pet:dragon'].filter(id=>u.rubyItems?.[id]>0).length,discoveries:['fishing','fountain','skipping'].filter(id=>u.islandDiscoveries?.[id]).length};}
function earned(u,now=Date.now()){const result={...u.advancements},values=metrics(u);for(const a of CATALOG)if(!result[a.id]&&count(values[a.metric])>=a.target)result[a.id]=now;return result;}
function record(u,activity,units=1,now=Date.now()){if(!CATALOG.some(a=>a.metric===activity)||!Number.isSafeInteger(units)||units<1)return {};const advancementStats={...u.advancementStats,[activity]:count(count(u.advancementStats?.[activity])+units)};return {advancementStats,advancements:earned({...u,advancementStats},now)};}
function profile(u,admin=false){const unlocked=earned(u),values=metrics(u),staff=require('./village-workforce').profile(u);return {username:u.username||'Island resident',islandName:u.islandName||'Unnamed island',footy:Number(u.balance)||0,rubies:require('./gem-wallet').whole(u.gems?.bronze),villagers:staff.total,availableVillagers:staff.available.length,level:require('./town-hall-progress').profile(u).level,earnedCount:Object.keys(unlocked).filter(id=>CATALOG.some(a=>a.id===id)).length,total:CATALOG.length,adminView:admin,badges:CATALOG.map(a=>a.secret&&!unlocked[a.id]&&!admin?{id:'secret',secret:true,locked:true}:{...a,earnedAt:unlocked[a.id]||null,progress:Math.min(a.target,count(values[a.metric]))})};}
module.exports={CATALOG,record,earned,profile};
