const CATALOG=[
 ['brawl30','Arena Regular','Win 30 ranked Brawls.','ranked win',30,'swords'],['brawl150','Arena Legend','Win 150 ranked Brawls.','ranked win',150,'crown'],
 ['mine100','Deep Delver','Collect 100 rubies from mines.','ruby mining',100,'pick'],['mine1000','Heart of the Mountain','Collect 1,000 rubies from mines.','ruby mining',1000,'gem',true],
 ['farm75','Green Fingers','Gather 75 farmhouse ingredients.','farm gathering',75,'leaf'],['cook25','Island Chef','Cook 25 pet meals.','meal cooked',25,'bowl'],['cook150','Grand Feast','Cook 150 pet meals.','meal cooked',150,'crown'],
 ['care40','Faithful Friend','Play with your pets 40 times.','pet play',40,'heart'],['journey20','Trail Keeper','Complete 20 pet journeys.','journey',20,'compass'],['journey100','Beyond the Horizon','Complete 100 pet journeys.','journey',100,'star',true],
 ['pack50','Curious Collector','Open 50 packs.','pack',50,'cards'],['ascend25','Rising Collection','Perform 25 ascensions.','ascension',25,'star'],['forge50','Forge Veteran','Convert cards 50 times.','conversion',50,'gem'],['amulet10','Master Jeweller','Craft 10 amulets.','amulet crafted',10,'gem'],
 ['time30','Keeper of Hours','Harvest 30 time boosts.','time bank work',30,'clock'],['vault60','Patient Banker','Earn 60 Footy through vault work.','vault work',60,'coin'],
 ['hall5','Growing Roots','Reach Town Hall level 5.','hall',5,'house'],['hall10','Island Architect','Reach Town Hall level 10.','hall',10,'crown'],['village30','A Thriving Village','Have 30 villagers.','villagers',30,'house'],['pets3','An Unlikely Family','Own all three companion species.','pets',3,'heart'],
 ['discover3','Off the Beaten Path','Discover all three island minigames.','discoveries',3,'compass',true]
,
 ["brawl75", "Arena Veteran", "Win 75 ranked Brawls.", "ranked win", 75, "swords"],
 ["brawl300", "Champion of the Isle", "Win 300 ranked Brawls.", "ranked win", 300, "swords"],
 ["brawl750", "Living Legend", "Win 750 ranked Brawls.", "ranked win", 750, "swords"],
 ["mine300", "Ruby Prospector", "Collect 300 rubies from mines.", "ruby mining", 300, "pick"],
 ["mine600", "Rich Veins", "Collect 600 rubies from mines.", "ruby mining", 600, "pick"],
 ["mine2500", "Mountain Treasury", "Collect 2,500 rubies from mines.", "ruby mining", 2500, "pick"],
 ["farm250", "Bountiful Fields", "Gather 250 farmhouse ingredients.", "farm gathering", 250, "leaf"],
 ["farm750", "Harvest Master", "Gather 750 farmhouse ingredients.", "farm gathering", 750, "leaf"],
 ["farm2000", "Breadbasket of the Isle", "Gather 2,000 farmhouse ingredients.", "farm gathering", 2000, "leaf"],
 ["cook75", "Kitchen Keeper", "Cook 75 pet meals.", "meal cooked", 75, "bowl"],
 ["cook400", "Celebrated Chef", "Cook 400 pet meals.", "meal cooked", 400, "bowl"],
 ["care100", "Best of Friends", "Play with your pets 100 times.", "pet play", 100, "heart"],
 ["care250", "A Lifetime of Fetch", "Play with your pets 250 times.", "pet play", 250, "heart"],
 ["journey50", "Seasoned Explorer", "Complete 50 pet journeys.", "journey", 50, "compass"],
 ["journey250", "World Wanderer", "Complete 250 pet journeys.", "journey", 250, "compass"],
 ["pack150", "Binder Builder", "Open 150 packs.", "pack", 150, "cards"],
 ["pack400", "Archive Keeper", "Open 400 packs.", "pack", 400, "cards"],
 ["pack1000", "Grand Collection", "Open 1,000 packs.", "pack", 1000, "cards"],
 ["ascend75", "Aiming Higher", "Perform 75 ascensions.", "ascension", 75, "star"],
 ["ascend200", "Beyond Ordinary", "Perform 200 ascensions.", "ascension", 200, "star"],
 ["forge150", "Crystal Artisan", "Convert cards 150 times.", "conversion", 150, "gem"],
 ["forge400", "Master of the Forge", "Convert cards 400 times.", "conversion", 400, "gem"],
 ["amulet25", "Enchanted Collection", "Craft 25 amulets.", "amulet crafted", 25, "gem"],
 ["amulet60", "Relic Master", "Craft 60 amulets.", "amulet crafted", 60, "gem"],
 ["time100", "Time Curator", "Harvest 100 time boosts.", "time bank work", 100, "clock"],
 ["time300", "An Age Saved", "Harvest 300 time boosts.", "time bank work", 300, "clock"],
 ["vault180", "Trusted Treasurer", "Earn 180 Footy through vault work.", "vault work", 180, "coin"],
 ["vault500", "Island Financier", "Earn 500 Footy through vault work.", "vault work", 500, "coin"],
 ["hall3", "Foundations", "Reach Town Hall level 3.", "hall", 3, "house"],
 ["hall7", "Island Township", "Reach Town Hall level 7.", "hall", 7, "house"],
 ["village15", "Friendly Neighbours", "Have 15 villagers.", "villagers", 15, "house"],
 ["village60", "Bustling Streets", "Have 60 villagers.", "villagers", 60, "house"],
 ["village100", "Everybody Is Home", "Have 100 villagers.", "villagers", 100, "house"],
 ["buy50", "Market Regular", "Earn marketplace purchase XP 50 times.", "market purchase", 50, "coin"],
 ["buy200", "Discerning Customer", "Earn marketplace purchase XP 200 times.", "market purchase", 200, "coin"],
 ["sell30", "Open for Business", "Earn marketplace sale XP 30 times.", "market sale", 30, "coin"],
 ["sell150", "Merchant of the Isle", "Earn marketplace sale XP 150 times.", "market sale", 150, "coin"],
 ["dye50", "Colour Collector", "Craft dye 50 times.", "dye crafting", 50, "gem"],
 ["dye200", "Prismatic Workshop", "Craft dye 200 times.", "dye crafting", 200, "gem"],
 ["paint30", "Personal Touch", "Apply dye 30 times.", "dye applied", 30, "star"],
 ["paint100", "Signature Style", "Apply dye 100 times.", "dye applied", 100, "star"],
 ["compress25", "Under Pressure", "Compress gems 25 times.", "compression", 25, "gem"],
 ["compress100", "Crystal Specialist", "Compress gems 100 times.", "compression", 100, "gem"],
 ["wheel100", "Turning Fortune", "Spin the wheel 100 times.", "wheel", 100, "star"],
 ["wheel365", "Full Circle", "Spin the wheel 365 times.", "wheel", 365, "star"],
 ["house5", "Room to Grow", "Upgrade villager houses 5 times.", "house upgrade", 5, "heart"],
 ["house15", "Village Planner", "Upgrade villager houses 15 times.", "house upgrade", 15, "heart"]
].map(([id,name,description,metric,target,icon,secret=false])=>({id,name,description,metric,target,icon,secret}));
const count=v=>Math.max(0,Math.min(Number.MAX_SAFE_INTEGER,Math.floor(Number(v)||0)));
function metrics(u){return {...u.advancementStats,hall:require('./town-hall-progress').profile(u).level,villagers:require('./village-workforce').residents(u).length,pets:['pet:fox','pet:snail','pet:dragon'].filter(id=>u.rubyItems?.[id]>0).length,discoveries:['fishing','fountain','skipping'].filter(id=>u.islandDiscoveries?.[id]).length};}
function earned(u,now=Date.now()){const result={...u.advancements},values=metrics(u);for(const a of CATALOG)if(!result[a.id]&&count(values[a.metric])>=a.target)result[a.id]=now;return result;}
function record(u,activity,units=1,now=Date.now()){if(!CATALOG.some(a=>a.metric===activity)||!Number.isSafeInteger(units)||units<1)return {};const advancementStats={...u.advancementStats,[activity]:count(count(u.advancementStats?.[activity])+units)};return {advancementStats,advancements:earned({...u,advancementStats},now)};}
function profile(u,admin=false){const unlocked=earned(u),values=metrics(u),staff=require('./village-workforce').profile(u);return {username:u.username||'Island resident',islandName:u.islandName||'Unnamed island',footy:Number(u.balance)||0,rubies:require('./gem-wallet').whole(u.gems?.bronze),villagers:staff.total,availableVillagers:staff.available.length,level:require('./town-hall-progress').profile(u).level,earnedCount:Object.keys(unlocked).filter(id=>CATALOG.some(a=>a.id===id)).length,total:CATALOG.length,adminView:admin,badges:CATALOG.map(a=>a.secret&&!unlocked[a.id]&&!admin?{id:'secret',secret:true,locked:true}:{...a,earnedAt:unlocked[a.id]||null,progress:Math.min(a.target,count(values[a.metric]))})};}
module.exports={CATALOG,record,earned,profile};
