const test=require('node:test'),assert=require('node:assert/strict'),rules=require('./marketplace-visibility');
test('listing group limits are per viewer and retain seller management visibility',()=>{const item={sellerId:'seller',listingGroupId:'group'},groups=new Map([['group',{perUserLimit:2,purchaseCounts:{a:2,b:1}}]]);assert.equal(rules.visible(item,'a',groups,new Set()),false);assert.equal(rules.visible(item,'b',groups,new Set()),true);assert.equal(rules.visible(item,'seller',groups,new Set()),true);assert.equal(rules.visible({...item,listingGroupId:'missing'},'b',groups,new Set()),false);});
test('one-per-player limits use the same identity as purchase validation',()=>{const item={sellerId:'seller',limitOnePerUser:true,itemType:'pack',packId:'daily'};const previous=[{...item,buyerId:'a',purchasedViaMarketplace:true,purchaseLimitKey:'pack:daily'}];assert.equal(rules.visible(item,'a',new Map(),rules.purchases(previous,'a')),false);assert.equal(rules.visible(item,'b',new Map(),rules.purchases(previous,'b')),true);assert.equal(rules.visible({...item,limitOnePerUser:false},'a',new Map(),rules.purchases(previous,'a')),true);});

test('GET marketplace hides reached limits before grouping and normalizes displayed gem prices',async()=>{
 const records={items:{limited:{sellerId:'seller',listingGroupId:'g',price:4,currency:'footy'},open:{sellerId:'seller',price:1.8,currency:'bronze'},once:{sellerId:'seller',limitOnePerUser:true,imageUrl:'/card.png',price:5}},users:{a:{marketPurchaseKeys:['card:card.png']},seller:{isAdmin:true}},marketListingGroups:{g:{perUserLimit:1,purchaseCounts:{a:1}}}};
 const snap=(name,id)=>({id,exists:!!records[name]?.[id],data:()=>records[name]?.[id]});
 const query=(name,filter)=>({doc:id=>({get:async()=>snap(name,id)}),where:(key,op,value)=>query(name,[key,value]),get:async()=>{const docs=Object.keys(records[name]||{}).filter(id=>!filter||records[name][id][filter[0]]===filter[1]).map(id=>snap(name,id));return {docs,forEach:fn=>docs.forEach(fn)};}});
 let handler;const source=require('node:fs').readFileSync('server.js','utf8'),start=source.indexOf("app.get('/items',"),end=source.indexOf('/* ------------------ ADMIN ITEM IMAGE',start);
 require('node:vm').runInNewContext(source.slice(start,end),{app:{get:(path,fn)=>handler=fn},db:{collection:query},require,console,...require('./marketplace-utils'),amuletEffects:()=>({}),discounted:p=>p,serializeDate:()=>null,sortCardsByTier:()=>{},getAscendTierConfig:async()=>[]});
 let result;await handler({header:()=> 'a'},{json:v=>result=v,status(){return this;},send:v=>{throw Error(v);}});assert.deepEqual(Array.from(result,i=>i.id),['open']);assert.equal(result[0].price,2);
 await handler({header:()=> 'b'},{json:v=>result=v,status(){return this;},send:v=>{throw Error(v);}});assert.equal(result.length,3);
});
