const test=require('node:test'),assert=require('node:assert/strict'),care=require('./pet-care'),economy=require('./village-economy'),journeys=require('./pet-journeys');
const user=()=>({townHallXP:8500,gems:{bronze:200},rubyItems:{'pet:fox':1,food:4,'food:trail':2,'food:feast':2},villageLayout:{'house:0':0,'house:1':2}});
const apply=(u,b,t=1000)=>Object.assign(u,economy.action(u,b,t));
test('farm upgrades cost 50/100 and enforce level and balance',()=>{const u=user();apply(u,{action:'farm-upgrade',level:1});assert.equal(u.gems.bronze,150);assert.throws(()=>apply(u,{action:'farm-upgrade',level:1}),/changed/);apply(u,{action:'farm-upgrade',level:2});assert.equal(u.gems.bronze,50);assert.equal(u.farmLevel,3);assert.throws(()=>apply(u,{action:'farm-upgrade',level:3}),/unavailable/);assert.throws(()=>apply({...user(),townHallXP:0},{action:'farm-upgrade',level:1}),/unavailable/);});
test('all ingredients use exact intervals and stop at three without duplicate collection',()=>{for(const [resource,r] of Object.entries(care.RESOURCES)){const u={...user(),farmLevel:3};apply(u,{action:'farm-start',house:'house:0',resource});const interval=r.minutes*60000;assert.equal(care.profile(u,1000+interval-1).farmJobs[0].claimable,0);apply(u,{action:'farm-collect',resource},1000+interval);assert.equal(u.farmIngredients[resource],1);apply(u,{action:'farm-collect',resource},1000+interval);assert.equal(u.farmIngredients[resource],1);apply(u,{action:'farm-collect',resource},1000+interval*8);assert.equal(u.farmIngredients[resource],3);assert.equal(care.profile(u,1000+interval*8).farmJobs.length,0);assert.throws(()=>apply(u,{action:'farm-collect',resource}),/not found/);}});
test('care, farming and mining reserve individuals from one shared pool',()=>{const u=user();apply(u,{action:'station-send',pet:'pet:fox'});apply(u,{action:'farm-start',resource:'carrot'});apply(u,{action:'start-mine'});assert.equal(economy.profile(u,1000).workforce.available.length,0);const ids=[...u.petStation.workers,...u.farmJobs.carrot.workers,...u.rubyMineShifts[0].workers];assert.equal(new Set(ids).size,6);assert.throws(()=>apply(u,{action:'farm-start',resource:'water'}),/2 available/);apply(u,{action:'farm-recall',resource:'carrot'},2401000);assert.equal(u.farmIngredients.carrot,1);assert.equal(economy.profile(u,2401000).workforce.available.length,2);apply(u,{action:'station-recall'},2401000);assert.equal(economy.profile(u,2401000).workforce.available.length,3);});
test('multiple resources can run concurrently and stop after three units',()=>{const u=user();apply(u,{action:'farm-start',resource:'water'});apply(u,{action:'farm-start',resource:'carrot'});assert.equal(economy.profile(u,1000).workforce.available.length,2);assert.equal(u.farmJobs.water.workers.length,2);assert.equal(u.farmJobs.carrot.workers.length,2);assert.equal(economy.profile(u,3601000).workforce.available.length,4);assert.equal(economy.profile(u,7201000).workforce.available.length,6);});
test('recipes consume exact ingredients and add existing journey foods',()=>{const u={...user(),farmLevel:3,farmIngredients:{water:2,carrot:1,corn:1,milk:1,meat:1}};for(const food of Object.keys(care.MEALS)){const before=u.rubyItems[food];apply(u,{action:'farm-cook',food});assert.equal(u.rubyItems[food],before+1);assert.throws(()=>apply(u,{action:'farm-cook',food}),/need/);}assert.deepEqual(u.farmIngredients,{water:0,carrot:0,corn:0,milk:0,meat:0});});
test('pet meals and play award persistent capped happiness without decay',()=>{const u=user();assert.throws(()=>apply(u,{action:'pet-play',pet:'pet:fox'}),/station/);apply(u,{action:'station-send',house:'house:0',pet:'pet:fox'});for(const [food,total] of [['food',1],['food:trail',3],['food:feast',7]]){apply(u,{action:'pet-feed',pet:'pet:fox',food},1000+total*7200000);assert.equal(care.happiness(u,'pet:fox'),total);}assert.equal(care.profile(u).pets[0].multiplier,3);apply(u,{action:'pet-play',pet:'pet:fox'});assert.equal(care.happiness(u,'pet:fox'),8);apply(u,{action:'pet-feed',pet:'pet:fox',food:'food:feast'},1000+10*7200000);assert.equal(care.happiness(u,'pet:fox'),10);assert.equal(care.profile(u,9999999999999).pets[0].multiplier,5);assert.throws(()=>apply(u,{action:'pet-play',pet:'pet:fox'}),/maximum/);});
test('happiness boosts real normalized exploration odds and station pets cannot travel',()=>{const table=journeys.tables([{id:'b',name:'Bronze',order:0},{id:'s',name:'Silver',order:1}],[])[0];const a=journeys.petOdds(table,'pet:fox',0),b=journeys.petOdds(table,'pet:fox',10);for(const rows of [b.gems,b.quantities,b.rewards])assert.equal(rows.reduce((n,r)=>n+r.weight,0),1000000);const ratio=t=>t.gems[1].weight/t.gems[0].weight;assert.ok(Math.abs(ratio(b)/ratio(a)-5)<.001);const u=user();apply(u,{action:'station-send',house:'house:0',pet:'pet:fox'});assert.throws(()=>journeys.start(u,'pet:fox','food',[table],'trip'),/station/);apply(u,{action:'station-recall'});u.petHappiness={'pet:fox':10};const result=journeys.start(u,'pet:fox','food',[table],'trip',1000,[600000,400000,0]);assert.equal(result.petJourneys['pet:fox'].happinessMultiplier,5);assert.equal(result.petJourneys['pet:fox'].reward.gemKey,'silver');});

test('care cooldowns persist independently and unlock exactly at the boundary',()=>{const u=user();apply(u,{action:'station-send',pet:'pet:fox'});apply(u,{action:'pet-play',pet:'pet:fox'});apply(u,{action:'pet-feed',pet:'pet:fox',food:'food'});const copy=JSON.parse(JSON.stringify(u));assert.throws(()=>apply(copy,{action:'pet-play',pet:'pet:fox'},3600999),/available in/);assert.throws(()=>apply(copy,{action:'pet-feed',pet:'pet:fox',food:'food'},7200999),/available in/);apply(copy,{action:'pet-play',pet:'pet:fox'},32401000);apply(copy,{action:'pet-feed',pet:'pet:fox',food:'food'},7201000);assert.equal(copy.rubyItems.food,2);});
test('farmhouse tiers require Town Hall five and six',()=>{const u={...user(),townHallXP:4000,townHallProgressVersion:3};assert.throws(()=>apply(u,{action:'farm-upgrade',level:1}),/level 5/);u.townHallXP=8000;apply(u,{action:'farm-upgrade',level:1});assert.throws(()=>apply(u,{action:'farm-upgrade',level:2}),/level 6/);u.townHallXP=14000;apply(u,{action:'farm-upgrade',level:2});assert.equal(u.farmLevel,3);});

test('new gathering uses slower rates while existing shifts keep their original timing',()=>{assert.deepEqual(Object.fromEntries(Object.entries(care.RESOURCES).map(([k,v])=>[k,v.minutes])),{water:20,carrot:40,corn:80,milk:120,meat:240});const u={...user(),farmJobs:{water:{started:1000,ends:901000,claimed:0,workers:['house:0/0','house:0/1']}}};assert.equal(care.profile(u,301000).farmJobs[0].claimable,1);assert.equal(care.profile(u,901000).farmJobs[0].claimable,3);});
