const test=require('node:test'),assert=require('node:assert/strict'),care=require('./pet-care'),economy=require('./village-economy'),journeys=require('./pet-journeys');
const user=()=>({townHallXP:8500,gems:{bronze:200},rubyItems:{'pet:fox':1,food:4,'food:trail':2,'food:feast':2},villageLayout:{'house:0':0,'house:1':2}});
const apply=(u,b,t=1000)=>Object.assign(u,economy.action(u,b,t));
test('farm upgrades cost 50/100 and enforce level and balance',()=>{const u=user();apply(u,{action:'farm-upgrade',level:1});assert.equal(u.gems.bronze,150);assert.throws(()=>apply(u,{action:'farm-upgrade',level:1}),/changed/);apply(u,{action:'farm-upgrade',level:2});assert.equal(u.gems.bronze,50);assert.equal(u.farmLevel,3);assert.throws(()=>apply(u,{action:'farm-upgrade',level:3}),/unavailable/);assert.throws(()=>apply({...user(),townHallXP:0},{action:'farm-upgrade',level:1}),/unavailable/);});
test('all ingredients use exact intervals and stop at three without duplicate collection',()=>{for(const [resource,r] of Object.entries(care.RESOURCES)){const u={...user(),farmLevel:3};apply(u,{action:'farm-start',house:'house:0',resource});const interval=r.minutes*60000;assert.equal(care.profile(u,1000+interval-1).farmJobs[0].claimable,0);apply(u,{action:'farm-collect',resource},1000+interval);assert.equal(u.farmIngredients[resource],1);apply(u,{action:'farm-collect',resource},1000+interval);assert.equal(u.farmIngredients[resource],1);apply(u,{action:'farm-collect',resource},1000+interval*8);assert.equal(u.farmIngredients[resource],3);assert.equal(care.profile(u,1000+interval*8).farmJobs.length,0);assert.throws(()=>apply(u,{action:'farm-collect',resource}),/not found/);}});
test('care, farming and mining cannot share households; recall frees workers',()=>{const u=user();apply(u,{action:'station-send',house:'house:0',pet:'pet:fox'});assert.throws(()=>apply(u,{action:'start-household',house:'house:0'}),/already/);assert.throws(()=>apply(u,{action:'farm-start',house:'house:0',resource:'water'}),/available/);apply(u,{action:'farm-start',house:'house:1',resource:'carrot'});assert.throws(()=>apply(u,{action:'start-household',house:'house:1'}),/already/);apply(u,{action:'farm-recall',resource:'carrot'},601000);assert.equal(u.farmIngredients.carrot,1);apply(u,{action:'start-household',house:'house:1'},601000);apply(u,{action:'station-recall'},601000);assert.equal(care.profile(u,601000).station,null);});
test('recipes consume exact ingredients and add existing journey foods',()=>{const u={...user(),farmLevel:3,farmIngredients:{water:2,carrot:1,corn:1,milk:1,meat:1}};for(const food of Object.keys(care.MEALS)){const before=u.rubyItems[food];apply(u,{action:'farm-cook',food});assert.equal(u.rubyItems[food],before+1);assert.throws(()=>apply(u,{action:'farm-cook',food}),/need/);}assert.deepEqual(u.farmIngredients,{water:0,carrot:0,corn:0,milk:0,meat:0});});
test('pet meals and play award persistent capped happiness without decay',()=>{const u=user();assert.throws(()=>apply(u,{action:'pet-play',pet:'pet:fox'}),/station/);apply(u,{action:'station-send',house:'house:0',pet:'pet:fox'});for(const [food,total] of [['food',1],['food:trail',3],['food:feast',7]]){apply(u,{action:'pet-feed',pet:'pet:fox',food});assert.equal(care.happiness(u,'pet:fox'),total);}assert.equal(care.profile(u).pets[0].multiplier,3);apply(u,{action:'pet-play',pet:'pet:fox'});assert.equal(care.happiness(u,'pet:fox'),8);apply(u,{action:'pet-feed',pet:'pet:fox',food:'food:feast'});assert.equal(care.happiness(u,'pet:fox'),10);assert.equal(care.profile(u,9999999999999).pets[0].multiplier,5);assert.throws(()=>apply(u,{action:'pet-play',pet:'pet:fox'}),/maximum/);});
test('happiness boosts real normalized exploration odds and station pets cannot travel',()=>{const table=journeys.tables([{id:'b',name:'Bronze',order:0},{id:'s',name:'Silver',order:1}],[])[0];const a=journeys.petOdds(table,'pet:fox',0),b=journeys.petOdds(table,'pet:fox',10);for(const rows of [b.gems,b.quantities,b.rewards])assert.equal(rows.reduce((n,r)=>n+r.weight,0),1000000);const ratio=t=>t.gems[1].weight/t.gems[0].weight;assert.ok(Math.abs(ratio(b)/ratio(a)-5)<.001);const u=user();apply(u,{action:'station-send',house:'house:0',pet:'pet:fox'});assert.throws(()=>journeys.start(u,'pet:fox','food',[table],'trip'),/station/);apply(u,{action:'station-recall'});u.petHappiness={'pet:fox':10};const result=journeys.start(u,'pet:fox','food',[table],'trip',1000,[400000,400000,0]);assert.equal(result.petJourneys['pet:fox'].happinessMultiplier,5);assert.equal(result.petJourneys['pet:fox'].reward.gemKey,'silver');});
