const shop=require('./ruby-shop'),wardrobe=require('./public/wardrobe');
const DAY=86400000,round=n=>Math.round(n*100)/100;
function catalog(tiers=[]){return [...shop.CATALOG.map(i=>({...i,key:'ruby:'+i.id,field:'rubyItems',currency:i.currency==='Footy'?'Footy':'bronze',currencyName:i.currency==='Footy'?'Footy':'Rubies',unique:i.kind!=='supply'})),...Object.entries({water:2,carrot:4,corn:8,milk:12,meat:24}).map(([id,price])=>({id,key:'farm:'+id,field:'farmIngredients',name:id,price,currency:'Footy',currencyName:'Footy'})),...require('./amulet-utils').catalog(tiers).map(i=>({...i,key:'amulet:'+i.id,field:'amulets',currency:i.exclusive?'Footy':i.gemKey,currencyName:i.exclusive?'Footy':i.gemName,price:i.exclusive?100:i.price})),...tiers.map((t,i)=>{const g=require('./gem-utils').gemIdentity(t);return {id:g.gemKey,key:'dye:'+g.gemKey,field:'gemDyes',name:g.gemName+' dye',price:5*(i+1),currency:'Footy',currencyName:'Footy'};})];}
function protectedItem(user,item,decor={}){if(item.field==='amulets')return (user.amuletSlots||[]).some(s=>s?.id===item.id);if(item.field!=='rubyItems')return false;if(item.kind==='clothing')return require('./public/hall-world').character(user.townHallCharacter)[item.slot]===item.value;if(item.kind==='pet')return user.petStation?.pet===item.id||user.petJourneys?.[item.id]?.status==='travelling'||require('./pet-journeys').pets(user).includes(item.id);if(item.kind==='relic')return Object.values(decor).some(d=>d.item===item.id&&d.owner===user.id);return Object.values(user.rubyEquipped||{}).includes(item.id)||(item.id==='fuel'&&user.rubyFuelArmed);}
function inventory(user,tiers,decor={}){user={...user,gemDyes:require('./gem-workshop-utils').dyeInventory(user)};return catalog(tiers).map(i=>({...i,price:round(i.price*.9),quantity:Math.max(0,Math.floor(Number(user[i.field]?.[i.id])||0)),blocked:protectedItem(user,i,decor)})).filter(i=>i.quantity>0);}
function count(stall){return (stall.entries||[]).reduce((n,e)=>n+e.quantity,0);}
function rate(stall){const n=(stall.entries||[]).filter(e=>!e.pack).reduce((n,e)=>n+e.quantity,0);return n?Math.min(4,1+Math.floor(Math.log10(n))):0;}
function money(user,currency,delta){if(currency==='Footy')user.balance=round((Number(user.balance)||0)+delta);else user.gems={...(user.gems||{}),[currency]:round((Number(user.gems?.[currency])||0)+delta)};}
function funds(user,currency){return Number(currency==='Footy'?user.balance:user.gems?.[currency])||0;}
function add(user,item,amount){if(item.field==='gemDyes')user.gemDyes=require('./gem-workshop-utils').dyeInventory(user);user[item.field]={...(user[item.field]||{}),[item.id]:Math.max(0,(Number(user[item.field]?.[item.id])||0)+amount)};}
function settle(user,stall,now=Date.now(),random=()=>require('node:crypto').randomInt(1000000)/1000000){stall.entries=(stall.entries||[]).map(e=>({...e}));let at=Number(stall.npcAt)||now,sales=0;at=Math.max(at,now-7*DAY);while(rate(stall)&&sales<28){const interval=DAY/rate(stall);if(at+interval>now)break;at+=interval;const eligible=stall.entries.filter(e=>!e.pack&&e.quantity>0);const pick=eligible[Math.min(eligible.length-1,Math.floor(random()*eligible.length))];pick.quantity--;money(user,pick.currency,pick.price);sales++;stall.history=[{name:pick.name,price:pick.price,currencyName:pick.currencyName,at,buyer:'Villager'},...(stall.history||[])].slice(0,20);stall.entries=stall.entries.filter(e=>e.quantity>0);}stall.npcAt=rate(stall)?at:now;stall.stockCount=count(stall);return sales;}
function buy(buyer,seller,stall,key,now){const item=stall.entries.find(e=>e.key===key&&e.quantity>0);if(!item)throw Error('This item has sold out.');const meal=require('./pet-care').MEALS[item.id];if(meal){const care=require('./pet-care').profile(buyer);if(!care.farmUnlocked||care.farmLevel<meal.tier)throw Error('Unlock this food in the farmhouse first.');}if(item.unique&&((buyer[item.field]?.[item.id]||0)>0||(item.kind==='clothing'&&wardrobe.owns(buyer,item))))throw Error('You already own this item.');if(funds(buyer,item.currency)<item.price)throw Error('Not enough '+item.currencyName+'.');money(buyer,item.currency,-item.price);money(seller,item.currency,item.price);if(!item.pack)add(buyer,item,1);item.quantity--;stall.entries=stall.entries.filter(e=>e.quantity);stall.stockCount=count(stall);stall.history=[{name:item.name,price:item.price,currencyName:item.currencyName,at:now,buyer:'Player'},...(stall.history||[])].slice(0,20);return item;}
module.exports={catalog,inventory,protectedItem,count,rate,settle,buy,add,round,DAY};
