const test=require('node:test'),assert=require('node:assert/strict'),rules=require('./player-stall');
const tiers=[{id:'bronze',name:'Bronze',sellPrice:20,packs:['bronze-pack']}];
function harness(){let data={'users/a':{username:'Alice',balance:100,gems:{bronze:200},rubyItems:{'relic:rose':1,food:5,'outfit:mariner':1},farmIngredients:{water:4},townHallXP:8500,farmLevel:3},'users/b':{username:'Ben',balance:100,gems:{bronze:200},townHallXP:8500,farmLevel:3},'users/c':{username:'Cara',balance:100,gems:{bronze:200},townHallXP:8500,farmLevel:3},'items/p1':{buyerId:'a',sold:true,itemType:'pack',packId:'bronze-pack',name:'Bronze pack'},'items/card':{buyerId:'a',sold:true,itemType:'card',name:'Card'}};const handlers={};let queue=Promise.resolve();
 const ref=key=>({key,id:key.split('/').at(-1),get:async()=>snap(key,data)}),snap=(key,source)=>({id:key.split('/').at(-1),ref:ref(key),exists:!!source[key],data:()=>source[key]&&structuredClone(source[key])});
 function query(name,filters=[],after='',limit=Infinity){return {doc:id=>ref(name+'/'+id),where:(field,op,value)=>query(name,[...filters,[field,op,value]],after,limit),orderBy:()=>query(name,filters,after,limit),startAfter:id=>query(name,filters,id,limit),limit:n=>query(name,filters,after,n),get:async()=>({docs:Object.keys(data).filter(k=>k.startsWith(name+'/')&&k.split('/')[1]>after&&filters.every(([f,op,v])=>op==='=='?data[k][f]===v:data[k][f]>v)).sort().slice(0,limit).map(k=>snap(k,data))})};}
 const db={collection:query,runTransaction:fn=>{const run=queue.then(async()=>{const work=structuredClone(data);let written=false;const result=await fn({get:async r=>{assert.equal(written,false,'all reads before writes');return snap(r.key,work);},set:(r,v)=>{written=true;assert.ok(!JSON.stringify(v).includes('undefined'));work[r.key]=structuredClone(v);},update:(r,v)=>{written=true;if(!work[r.key])throw Error('Missing document');Object.assign(work[r.key],structuredClone(v));}});data=work;return result;});queue=run.catch(()=>{});return run;}};
 require('./player-stall-routes')({get:(p,f)=>handlers['GET'+p]=f,post:(p,f)=>handlers['POST'+p]=f},db,async req=>{if(!req.id)throw Error('Login required');return req.id;},async()=>tiers);
 let serial=0;async function call(id,body,query){let status=200,value;const res={status:n=>{status=n;return res;},json:v=>value=v,send:v=>value=v};await handlers[(body?'POST/player-stall/action':'GET/player-stall')]({id,body:body&&{actionId:'stall-action-test-'+(++serial),...body},query},res);return {status,value};}
 return {call,get data(){return data;}};
}
test('listings escrow goods, ignore supplied prices, withdraw and deduplicate safely',async()=>{const h=harness();assert.equal((await h.call(null)).status,400);const b={action:'list',key:'ruby:relic:rose',quantity:1,price:999,actionId:'same-action-test-123'};assert.equal((await h.call('a',b)).status,200);await h.call('a',b);assert.equal(h.data['users/a'].rubyItems['relic:rose'],0);assert.equal(h.data['playerStalls/a'].entries[0].price,135);assert.equal((await h.call('a',{action:'list',key:'pack:card',quantity:1})).status,400);assert.equal((await h.call('a',{action:'withdraw',key:b.key})).status,200);assert.equal(h.data['users/a'].rubyItems['relic:rose'],1);assert.equal(h.data['playerStalls/a'].stockCount,0);});
test('two buyers cannot buy the same last good and currencies transfer exactly',async()=>{const h=harness();await h.call('a',{action:'list',key:'ruby:relic:rose',quantity:1});const results=await Promise.all(['b','c'].map(id=>h.call(id,{action:'buy',seller:'a',key:'ruby:relic:rose'})));assert.deepEqual(results.map(r=>r.status),[200,400]);assert.equal(h.data['users/a'].gems.bronze,335);assert.equal(h.data['users/b'].gems.bronze,65);assert.equal(h.data['users/b'].rubyItems['relic:rose'],1);assert.equal(h.data['playerStalls/a'].stockCount,0);});
test('packs escrow and transfer ownership, never eligible for villager purchases',async()=>{const h=harness();await h.call('a',{action:'list',key:'pack:p1',quantity:1});assert.equal(h.data['items/p1'].listedForSale,true);const stall=h.data['playerStalls/a'];assert.equal(rules.rate(stall),0);stall.npcAt=Date.now()-3*rules.DAY;assert.equal(rules.settle({},stall),0);assert.equal((await h.call('b',{action:'buy',seller:'a',key:'pack:p1'})).status,200);assert.equal(h.data['items/p1'].buyerId,'b');assert.equal(h.data['items/p1'].listedForSale,false);assert.equal(h.data['users/b'].balance,46);});
test('villager sales accrue daily, scale with stock, cap offline time and do not repeat',()=>{const user={gems:{bronze:0}},stall={npcAt:1000,entries:[{name:'Rose',id:'relic:rose',field:'rubyItems',quantity:3,price:135,currency:'bronze',currencyName:'Rubies'}]};assert.equal(rules.settle(user,stall,1000+rules.DAY-1,()=>0),0);assert.equal(rules.settle(user,stall,1000+rules.DAY,()=>0),1);assert.equal(user.gems.bronze,135);assert.equal(rules.settle(user,stall,1000+rules.DAY,()=>0),0);assert.equal(rules.settle(user,stall,1000+4*rules.DAY,()=>0),2);assert.equal(stall.stockCount,0);assert.equal(user.gems.bronze,405);const large={npcAt:1000,entries:[{quantity:1000,price:1,currency:'Footy',name:'Water'}]};assert.equal(rules.rate(large),4);assert.ok(rules.settle({},large,1000+100*rules.DAY,()=>0)<=28);});
test('equipped clothing, active pets and lent relics cannot be listed',async()=>{const h=harness();h.data['users/a'].townHallCharacter={outfit:'mariner'};assert.equal((await h.call('a',{action:'list',key:'ruby:outfit:mariner',quantity:1})).status,400);h.data['communityRooms/town-hall']={decor:{0:{owner:'a',item:'relic:rose'}}};assert.equal((await h.call('a',{action:'list',key:'ruby:relic:rose',quantity:1})).status,400);h.data['users/a'].rubyItems['pet:fox']=1;h.data['users/a'].petStation={pet:'pet:fox'};assert.equal((await h.call('a',{action:'list',key:'ruby:pet:fox',quantity:1})).status,400);});
test('clothing listings use Footy and player food purchases obey farmhouse unlocks',async()=>{const h=harness();await h.call('a',{action:'list',key:'ruby:outfit:mariner',quantity:1});await h.call('b',{action:'buy',seller:'a',key:'ruby:outfit:mariner'});assert.equal(h.data['users/a'].balance,122.5);assert.equal(h.data['users/b'].balance,77.5);assert.equal(h.data['users/a'].gems.bronze,200);await h.call('a',{action:'list',key:'ruby:food',quantity:1});h.data['users/c'].townHallXP=0;assert.equal((await h.call('c',{action:'buy',seller:'a',key:'ruby:food'})).status,400);});
module.exports={harness};

test('current game pack prices override fallback and legacy dyes remain tradable',async()=>{const h=harness();h.data['items/daily']={dailyPackDate:require('./daily-packs').dayKey(new Date()),itemType:'pack',packId:'bronze-pack',price:30};await h.call('a',{action:'list',key:'pack:p1',quantity:1});assert.equal(h.data['playerStalls/a'].entries[0].price,27);h.data['users/a'].gemDyes=['bronze'];const view=await h.call('a');assert.equal(view.value.inventory.find(i=>i.key==='dye:bronze').quantity,5);await h.call('a',{action:'list',key:'dye:bronze',quantity:2});assert.equal(h.data['users/a'].gemDyes.bronze,3);await h.call('a',{action:'withdraw',key:'dye:bronze'});assert.equal(h.data['users/a'].gemDyes.bronze,5);});
test('browsing paginates and long absence settlement credits only once',async()=>{const h=harness();for(let i=0;i<55;i++)h.data['playerStalls/z'+String(i).padStart(3,'0')]={stockCount:0,entries:[]};const first=await h.call('a');assert.ok(first.value.next);const next=await h.call('a',null,{after:first.value.next});assert.equal(next.value.next,null);await h.call('a',{action:'list',key:'ruby:food',quantity:5});h.data['playerStalls/a'].npcAt=Date.now()-2*rules.DAY-1000;const before=h.data['users/a'].gems.bronze;const paid=await h.call('a');assert.equal(paid.value.sales,2);assert.equal(h.data['users/a'].gems.bronze,Math.round((before+3.6)*100)/100);assert.equal((await h.call('a')).value.sales,0);});
