const test=require('node:test'),assert=require('node:assert/strict'),bank=require('./time-bank'),economy=require('./village-economy'),care=require('./pet-care');
const H=3600000,now=1000000;
const user=()=>({townHallXP:8500,villageLayout:{'house:0':0,'house:1':2},villageHouseTiers:{'house:0':3,'house:1':3},rubyItems:{'pet:fox':1,'pet:snail':1,'pet:dragon':1,food:3}});
const apply=(u,b,t=now)=>Object.assign(u,economy.action(u,b,t));
test('production duration and leap odds interpolate linearly at every worker count',()=>{for(let n=1;n<=10;n++){assert.ok(Math.abs(bank.interval(n)-(5-(n-1)*2.5/9)*H)<.001);assert.ok(Math.abs(bank.chance(n)-(.05+(n-1)*.1/9))<1e-12);}assert.throws(()=>bank.action({...user(),townHallXP:300},{action:'bank-set',count:1},now),/Town Hall 4/);});
test('production is stable, stops at three, and cannot harvest twice or accumulate overflow',()=>{const u=user();apply(u,{action:'bank-set',count:1});u.timeBank.rolls=[.01,.1,.9];const t=now+30*H;assert.deepEqual(bank.profile(u,t).stored,['leap','skip','skip']);assert.deepEqual(bank.profile(u,t).stored,bank.profile(u,t).stored);apply(u,{action:'bank-collect'},t);assert.deepEqual(u.timeBoosts,{skip:2,leap:1});assert.equal(bank.profile(u,t).nextAt,t+5*H);assert.throws(()=>apply(u,{action:'bank-collect'},t),/No time/);});
test('worker changes preserve partial progress and reserve distinct villagers until recalled',()=>{const u=user();apply(u,{action:'bank-set',count:1});apply(u,{action:'bank-set',count:10},now+2.5*H);assert.equal(u.timeBank.progress,.5);assert.equal(bank.profile(u,now+2.5*H).nextAt,now+3.75*H);apply(u,{action:'start-mine'},now+2.5*H);assert.equal(new Set([...u.timeBank.workers,...u.rubyMineShifts[0].workers]).size,13);apply(u,{action:'bank-set',count:0},now+2.5*H);assert.equal(economy.profile(u,now+2.5*H).workforce.available.length,17);assert.equal(u.timeBank.progress,.5);assert.throws(()=>apply(u,{action:'bank-set',count:11}),/between/);});
test('boosts advance mine, legacy farm and vault exactly once and never change farm yield intervals',()=>{const u=user();u.timeBoosts={skip:3,leap:1};apply(u,{action:'start-mine'});apply(u,{action:'time-use',token:'skip',target:'mine/0'});assert.equal(economy.profile(u,now).mines[0].claimable,4);apply(u,{action:'collect-mine',mine:0});assert.equal(economy.profile(u,now).mines[0].claimable,0);u.farmJobs={water:{started:now,ends:now+900000,claimed:0,workers:['house:1/0','house:1/1']}};apply(u,{action:'time-use',token:'skip',target:'farm/water'});assert.equal(u.farmJobs.water.ends-u.farmJobs.water.started,900000);assert.equal(care.profile(u,now).farmJobs[0].claimable,3);assert.throws(()=>apply(u,{action:'time-use',token:'skip',target:'farm/water'}),/active/);apply(u,{action:'vault-start'});apply(u,{action:'time-use',token:'leap',target:'vault'});assert.equal(u.vaultJob.started,now-H);assert.throws(()=>apply(u,{action:'time-use',token:'leap',target:'vault'}),/do not own/);});
test('boosts work on journeys, care, fortune cooldown and Time Bank production',()=>{const u=user();u.timeBoosts={skip:4,leap:4};u.petJourneys={'pet:fox':{status:'travelling',endsAt:now+4*H}};u.petCareCooldowns={'pet:fox':{play:now+H,feed:now+2*H}};u.lastSpin=new Date(now);for(const target of ['journey/pet:fox','play/pet:fox','feed/pet:fox','spin'])apply(u,{action:'time-use',token:'leap',target});assert.equal(u.petJourneys['pet:fox'].endsAt,now+3*H);assert.equal(u.petCareCooldowns['pet:fox'].play,now);assert.equal(u.lastSpin.getTime(),now-H);apply(u,{action:'bank-set',count:10});apply(u,{action:'time-use',token:'skip',target:'bank'});assert.ok(Math.abs(u.timeBank.progress-(1/3)/2.5)<1e-9);});
test('all three pets get unique caretakers; recall affects only the selected pet and legacy saves migrate',()=>{const u=user();u.petStation={pet:'pet:fox',workers:['house:0/0'],started:now};apply(u,{action:'station-send',pet:'pet:snail'});apply(u,{action:'station-send',pet:'pet:dragon'});assert.equal(care.profile(u,now).stations.length,3);assert.equal(economy.profile(u,now).workforce.busy.length,3);assert.throws(()=>apply(u,{action:'station-send',pet:'pet:fox'}),/already/);assert.throws(()=>apply(u,{action:'station-recall'}),/Choose/);apply(u,{action:'station-recall',pet:'pet:snail'});assert.equal(care.profile(u,now).stations.length,2);assert.equal(care.profile(u,now).pets.find(p=>p.id==='pet:fox').inStation,true);apply(u,{action:'pet-feed',pet:'pet:dragon',food:'food'});assert.equal(u.petHappiness['pet:dragon'],1);});

test('retrying the same boost receipt cannot spend or advance twice',()=>{const u=user();u.timeBoosts={skip:3,leap:0};apply(u,{action:'start-mine'});const body={action:'time-use',token:'skip',target:'mine/0',actionId:'same-request-123456'};apply(u,body);const started=u.rubyMineShifts[0].started;apply(u,body);assert.equal(u.timeBoosts.skip,2);assert.equal(u.rubyMineShifts[0].started,started);});

test('time leaps advance the personal amulet removal lock',()=>{const u=user();u.amuletSlots=[{id:'charm',removableAt:now+5*24*H},null];u.timeBoosts={leap:1};apply(u,{action:'time-use',token:'leap',target:'amulet/0'});assert.equal(u.amuletSlots[0].removableAt,now+119*H);assert.equal(u.amuletSlots[1],null);});

test('harvesting awards two XP per produced boost and never on repeated collection',()=>{const u={...user(),townHallXP:650};apply(u,{action:'bank-set',count:1});apply(u,{action:'bank-collect'},now+15*H);assert.equal(u.townHallXP,656);assert.throws(()=>apply(u,{action:'bank-collect'},now+15*H),/No time/);assert.equal(u.townHallXP,656);});
