const test=require('node:test'),assert=require('node:assert/strict'),world=require('./public/hall-world');
function harness(){let now=100000,reads=0,transactions=0;const records={'users/a':{isAdmin:true,username:'Alice',rubyItems:{'relic:crown':1,food:20},gems:{bronze:100,gold:10}},'users/b':{isAdmin:true,username:'Ben',rubyItems:{'relic:books':1},gems:{bronze:100}},'users/c':{isAdmin:false,username:'Player'}};const handlers={};const snap=k=>({exists:!!records[k],data:()=>records[k]&&structuredClone(records[k])});const db={collection:n=>({doc:id=>({id,key:n+'/'+id,get:async()=>{reads++;return snap(n+'/'+id);},update:async v=>Object.assign(records[n+'/'+id],v)})}),runTransaction:async fn=>{transactions++;return fn({get:async r=>snap(r.key),set:(r,v)=>records[r.key]=v,update:(r,v)=>Object.assign(records[r.key],v)});}};
 const register=()=>require('./town-hall-routes')({get:(p,f)=>handlers['GET'+p]=f,post:(p,f)=>handlers['POST'+p]=f},db,async req=>{const id=req.header('X-User-Id');if(!id)throw Error('Login');return id;},()=>now);register();
 async function call(path,{id,token,body}={}){let status=200,value;const res={status(n){status=n;return res;},json(v){value=v;},send(v){value=v;}};await handlers[(body?'POST':'GET')+'/admin/town-hall/'+path]({body,header:k=>k==='X-User-Id'?id:k==='X-Hall-Token'?token:''},res);return {status,value};}
 return {records,call,restart:register,get transactions(){return transactions;},get reads(){return reads;},tick(n=1500){now+=n;},async join(id){return call('join',{id,body:{}});},async action(token,body){now+=1500;return call('action',{token,body});}};
}
test('authenticated players enter; two accounts share presence without per-poll Firestore reads',async()=>{const h=harness();assert.equal((await h.join()).status,401);assert.equal((await harness().join('c')).status,200);const a=(await h.join('a')).value,b=(await h.join('b')).value;assert.equal(b.members.length,2);const count=h.reads;for(let i=0;i<4;i++){h.tick();assert.equal((await h.call('state',{token:a.token})).status,200);}assert.equal(h.reads,count);h.tick(13000);assert.equal((await h.call('state',{token:a.token})).status,401);});
test('walking routes avoid the meeting table and seating is exclusive',async()=>{const h=harness(),a=(await h.join('a')).value,b=(await h.join('b')).value;const path=world.route({x:450,y:510},{x:450,y:180});assert.ok(path.every(p=>!world.blocked(p.x,p.y)));assert.throws(()=>world.route({x:450,y:510},{x:450,y:300}),/open/);assert.equal((await h.action(a.token,{type:'sit',seat:0})).status,200);assert.equal((await h.action(b.token,{type:'sit',seat:0})).status,400);assert.equal((await h.action(b.token,{type:'move',x:Infinity,y:5})).status,400);assert.equal((await h.action(a.token,{type:'stand'})).status,200);assert.equal((await h.action(b.token,{type:'sit',seat:0})).status,200);});
test('character saves are sanitized; chat and shelf decorations are shared with revision protection',async()=>{const h=harness(),a=(await h.join('a')).value,b=(await h.join('b')).value;await h.action(a.token,{type:'character',character:{skin:'forged',hair:world.HAIR[1],coat:world.COATS[0],style:'long'}});assert.equal(h.records['users/a'].townHallCharacter.skin,world.SKINS[0]);assert.equal(h.records['users/a'].townHallCharacter.style,'long');await h.action(a.token,{type:'chat',text:'Hello Ben'});assert.equal((await h.call('state',{token:b.token})).value.messages[0].text,'Hello Ben');assert.equal((await h.action(a.token,{type:'decorate',slot:0,item:'relic:crown',revision:0})).status,200);assert.equal((await h.action(b.token,{type:'decorate',slot:1,item:'relic:books',revision:0})).status,400);assert.equal((await h.action(b.token,{type:'decorate',slot:1,item:'relic:books',revision:1})).status,200);assert.equal(h.records['communityRooms/town-hall'].decor[0].item,'relic:crown');assert.equal((await h.action(b.token,{type:'level',level:6,revision:2})).status,400);assert.equal(h.records['users/a'].townHallXP,3);assert.equal(h.records['users/b'].townHallXP||0,0);});
test('seated invitations create exactly one compatible, zero-stake Skystones match',async()=>{const h=harness(),a=(await h.join('a')).value,b=(await h.join('b')).value;assert.equal((await h.action(a.token,{type:'invite',target:'b',averageLimit:30,timeControlSeconds:180})).status,400);await h.action(a.token,{type:'sit',seat:4});await h.action(b.token,{type:'sit',seat:5});h.tick(3000);const invited=await h.action(a.token,{type:'invite',target:'b',averageLimit:30,timeControlSeconds:180});assert.equal(invited.status,200);const id=invited.value.invites[0].id;assert.equal((await h.action(a.token,{type:'accept',inviteId:id})).status,400);const accepted=await h.action(b.token,{type:'accept',inviteId:id});assert.equal(accepted.status,200);assert.equal((await h.action(b.token,{type:'accept',inviteId:id})).status,200);const keys=Object.keys(h.records).filter(k=>k.startsWith('battleMatches/'));assert.equal(keys.length,1);const match=h.records[keys[0]];assert.equal(match.status,'setup');assert.equal(match.prize,0);assert.equal(match.averageLimit,30);assert.deepEqual(match.participantIds,['a','b']);assert.equal(match.board.length,16);assert.equal(accepted.value.members.find(m=>m.id==='a').matchId,keys[0].split('/')[1]);});

test('retired projects cannot spend resources; display progression stays private',async()=>{const h=harness(),a=(await h.join('a')).value,b=(await h.join('b')).value;h.records['users/a'].townHallXP=99;const rejected=await h.action(a.token,{type:'project',project:'stonework',actionId:'test-project-action-0001'});assert.equal(rejected.status,400);assert.equal(h.records['users/a'].gems.bronze,100);const displayed=await h.action(a.token,{type:'decorate',slot:0,item:'relic:crown',revision:0});assert.equal(displayed.value.progress.level,1);assert.equal((await h.call('state',{token:b.token})).value.progress.level,1);});

test('wardrobe changes reject unowned equipment and allow purchased accessories',async()=>{const h=harness(),a=(await h.join('a')).value;assert.equal((await h.action(a.token,{type:'character',character:{jewellery:'ruby'}})).status,400);h.records['users/a'].rubyItems['wardrobe:jewellery:ruby']=1;assert.equal((await h.action(a.token,{type:'character',character:{jewellery:'ruby'}})).status,200);assert.equal(h.records['users/a'].townHallCharacter.jewellery,'ruby');});

const displays=require('./hall-displays');
test('display lifespan is triangular, bounded 3-7 days and centred on five',()=>{assert.equal(displays.cycle(0,()=>0).remaining,3*displays.DAY);assert.equal(displays.cycle(0,()=>1).remaining,7*displays.DAY);assert.equal(displays.cycle(0,()=>.5).remaining,5*displays.DAY);});
test('display ticks accrue exactly once, stop at breakage, and preserve partial periods',()=>{let d={...displays.resume(displays.cycle(0,()=>.5),0),item:'relic:crown'};assert.equal(displays.advance(d,displays.rates(d.item).period-1).xp,0);let r=displays.advance(d,displays.rates(d.item).period);assert.equal(r.xp,4);assert.equal(displays.advance(r.display,displays.PERIOD).xp,0);r=displays.advance(r.display,9*displays.DAY);assert.equal(r.xp,80);assert.equal(r.display.broken,true);assert.equal(displays.advance(r.display,10*displays.DAY).xp,0);});
test('offline catch-up destroys broken collectible; anyone can clean once',async()=>{const h=harness(),a=(await h.join('a')).value;await h.action(a.token,{type:'decorate',slot:0,item:'relic:crown',revision:0});const display=h.records['communityRooms/town-hall'].decor[0],expected=Math.floor(display.remaining/displays.rates(display.item).period)*4;h.tick(8*displays.DAY);const b=(await h.join('b')).value;assert.equal(b.room.decor[0].broken,true);assert.equal(h.records['users/a'].rubyItems['relic:crown'],0);assert.equal(h.records['users/a'].townHallXP,expected);assert.equal((await h.action(b.token,{type:'clean-display',slot:0,revision:b.room.revision})).status,200);assert.equal(h.records['users/b'].townHallXP,3);assert.equal((await h.action(b.token,{type:'clean-display',slot:0,revision:b.room.revision})).status,400);assert.equal(h.records['users/b'].townHallXP,3);});
test('at most three displays per owner; other owners cannot remove them',async()=>{const h=harness();Object.assign(h.records['users/a'].rubyItems,{'relic:rose':1,'relic:moon':1,'relic:dragon':1});const a=(await h.join('a')).value;for(const [slot,item] of ['relic:crown','relic:rose','relic:moon'].entries())assert.equal((await h.action(a.token,{type:'decorate',slot,item,revision:slot})).status,200);assert.equal((await h.action(a.token,{type:'decorate',slot:3,item:'relic:dragon',revision:3})).status,400);const b=(await h.join('b')).value;assert.equal((await h.action(b.token,{type:'decorate',slot:0,item:null,revision:3})).status,400);});

test('visitor receipts survive server restarts and room polls do not repeat transactions',async()=>{const h=harness(),a=(await h.join('a')).value;await h.action(a.token,{type:'decorate',slot:0,item:'relic:crown',revision:0});let b=(await h.join('b')).value;const count=h.transactions;for(let i=0;i<4;i++){h.tick();await h.call('state',{token:b.token});}assert.equal(h.transactions,count);h.restart();await h.join('b');assert.equal(h.records['users/a'].townHallXP,3);});

test('displays cannot be taken down, replaced, or moved by their owner or admin',async()=>{const h=harness();h.records['users/a'].rubyItems['relic:rose']=1;const a=(await h.join('a')).value;await h.action(a.token,{type:'decorate',slot:0,item:'relic:crown',revision:0});for(const item of [null,'relic:rose','relic:crown'])assert.equal((await h.action(a.token,{type:'decorate',slot:0,item,revision:1})).status,400);assert.equal((await h.action(a.token,{type:'decorate',slot:1,item:'relic:crown',revision:1})).status,400);const b=(await h.join('b')).value;assert.equal((await h.action(b.token,{type:'decorate',slot:0,item:null,revision:1})).status,400);assert.equal(h.records['communityRooms/town-hall'].decor[0].item,'relic:crown');});
test('one-time shelf reset preserves owned items and never clears new displays after restart',async()=>{const h=harness();h.records['communityRooms/town-hall']={revision:4,decor:{0:{item:'relic:crown',owner:'a',by:'Alice'}}};let a=(await h.join('a')).value;assert.deepEqual(a.room.decor,{});assert.equal(h.records['users/a'].rubyItems['relic:crown'],1);assert.equal(h.records['users/a'].townHallXP||0,0);await h.action(a.token,{type:'decorate',slot:0,item:'relic:crown',revision:a.room.revision});h.restart();a=(await h.join('a')).value;assert.equal(a.room.decor[0].item,'relic:crown');});
test('every collectible advertises unique rewards and pays on its own interval',()=>{const items=require('./ruby-shop').CATALOG.filter(x=>x.kind==='relic');const unique=new Set();for(const item of items){const r=item.displayRewards;unique.add(JSON.stringify([r.periodic,r.hours,r.visitor,r.cleanup]));assert.match(item.description,new RegExp(r.periodic+' XP every '+r.hours+' hours'));const d={...displays.resume(displays.cycle(0,()=>.5),0),item:item.id};assert.equal(displays.advance(d,r.period-1).xp,0);assert.equal(displays.advance(d,r.period).xp,r.periodic);assert.equal(displays.advance(d,2*r.period).xp,2*r.periodic);}assert.equal(unique.size,items.length);const rose=displays.rates('relic:rose'),moon=displays.rates('relic:moon'),dragon=displays.rates('relic:dragon');assert.ok(rose.visitor>moon.visitor);assert.ok(moon.periodic/moon.hours>rose.periodic/rose.hours);assert.ok(dragon.visitor>rose.visitor);assert.ok(dragon.periodic/dragon.hours>moon.periodic/moon.hours);});
