const test=require('node:test'),assert=require('node:assert/strict'),world=require('./public/hall-world');
function harness(){let now=100000,reads=0;const records={'users/a':{isAdmin:true,username:'Alice',rubyItems:{'relic:crown':1,food:20},gems:{bronze:100,gold:10}},'users/b':{isAdmin:true,username:'Ben',rubyItems:{'relic:books':1},gems:{bronze:100}},'users/c':{isAdmin:false,username:'Player'}};const handlers={};const snap=k=>({exists:!!records[k],data:()=>records[k]&&structuredClone(records[k])});const db={collection:n=>({doc:id=>({id,key:n+'/'+id,get:async()=>{reads++;return snap(n+'/'+id);},update:async v=>Object.assign(records[n+'/'+id],v)})}),runTransaction:async fn=>fn({get:async r=>snap(r.key),set:(r,v)=>records[r.key]=v})};
 require('./town-hall-routes')({get:(p,f)=>handlers['GET'+p]=f,post:(p,f)=>handlers['POST'+p]=f},db,async req=>{const id=req.header('X-User-Id');if(!id)throw Error('Login');return id;},()=>now);
 async function call(path,{id,token,body}={}){let status=200,value;const res={status(n){status=n;return res;},json(v){value=v;},send(v){value=v;}};await handlers[(body?'POST':'GET')+'/admin/town-hall/'+path]({body,header:k=>k==='X-User-Id'?id:k==='X-Hall-Token'?token:''},res);return {status,value};}
 return {records,call,get reads(){return reads;},tick(n=1500){now+=n;},async join(id){return call('join',{id,body:{}});},async action(token,body){now+=1500;return call('action',{token,body});}};
}
test('only authenticated admins enter; two admins share presence without per-poll Firestore reads',async()=>{const h=harness();assert.equal((await h.join()).status,401);assert.equal((await h.join('c')).status,403);const a=(await h.join('a')).value,b=(await h.join('b')).value;assert.equal(b.members.length,2);const count=h.reads;for(let i=0;i<4;i++){h.tick();assert.equal((await h.call('state',{token:a.token})).status,200);}assert.equal(h.reads,count);h.tick(13000);assert.equal((await h.call('state',{token:a.token})).status,401);});
test('walking routes avoid the meeting table and seating is exclusive',async()=>{const h=harness(),a=(await h.join('a')).value,b=(await h.join('b')).value;const path=world.route({x:450,y:510},{x:450,y:180});assert.ok(path.every(p=>!world.blocked(p.x,p.y)));assert.throws(()=>world.route({x:450,y:510},{x:450,y:300}),/open/);assert.equal((await h.action(a.token,{type:'sit',seat:0})).status,200);assert.equal((await h.action(b.token,{type:'sit',seat:0})).status,400);assert.equal((await h.action(b.token,{type:'move',x:Infinity,y:5})).status,400);assert.equal((await h.action(a.token,{type:'stand'})).status,200);assert.equal((await h.action(b.token,{type:'sit',seat:0})).status,200);});
test('character saves are sanitized; chat and shelf decorations are shared with revision protection',async()=>{const h=harness(),a=(await h.join('a')).value,b=(await h.join('b')).value;await h.action(a.token,{type:'character',character:{skin:'forged',hair:world.HAIR[1],coat:world.COATS[2],style:'long'}});assert.equal(h.records['users/a'].townHallCharacter.skin,world.SKINS[0]);assert.equal(h.records['users/a'].townHallCharacter.style,'long');await h.action(a.token,{type:'chat',text:'Hello Ben'});assert.equal((await h.call('state',{token:b.token})).value.messages[0].text,'Hello Ben');assert.equal((await h.action(a.token,{type:'decorate',slot:0,item:'relic:crown',revision:0})).status,200);assert.equal((await h.action(b.token,{type:'decorate',slot:1,item:'relic:books',revision:0})).status,400);assert.equal((await h.action(b.token,{type:'decorate',slot:1,item:'relic:books',revision:1})).status,200);assert.equal(h.records['communityRooms/town-hall'].decor[0].item,'relic:crown');assert.equal((await h.action(b.token,{type:'level',level:6,revision:2})).status,400);assert.equal(h.records['users/a'].townHallXP,30);assert.equal(h.records['users/b'].townHallXP,30);});
test('seated invitations create exactly one compatible, zero-stake Skystones match',async()=>{const h=harness(),a=(await h.join('a')).value,b=(await h.join('b')).value;assert.equal((await h.action(a.token,{type:'invite',target:'b',averageLimit:30,timeControlSeconds:180})).status,400);await h.action(a.token,{type:'sit',seat:4});await h.action(b.token,{type:'sit',seat:5});h.tick(3000);const invited=await h.action(a.token,{type:'invite',target:'b',averageLimit:30,timeControlSeconds:180});assert.equal(invited.status,200);const id=invited.value.invites[0].id;assert.equal((await h.action(a.token,{type:'accept',inviteId:id})).status,400);const accepted=await h.action(b.token,{type:'accept',inviteId:id});assert.equal(accepted.status,200);assert.equal((await h.action(b.token,{type:'accept',inviteId:id})).status,200);const keys=Object.keys(h.records).filter(k=>k.startsWith('battleMatches/'));assert.equal(keys.length,1);const match=h.records[keys[0]];assert.equal(match.status,'setup');assert.equal(match.prize,0);assert.equal(match.averageLimit,30);assert.deepEqual(match.participantIds,['a','b']);assert.equal(match.board.length,16);assert.equal(accepted.value.members.find(m=>m.id==='a').matchId,keys[0].split('/')[1]);});

test('unowned decorations and duplicate display copies are rejected; removing and replacing never farms XP',async()=>{const h=harness(),a=(await h.join('a')).value;assert.equal((await h.action(a.token,{type:'decorate',slot:0,item:'relic:rose',revision:0})).status,400);await h.action(a.token,{type:'decorate',slot:0,item:'relic:crown',revision:0});assert.equal((await h.action(a.token,{type:'decorate',slot:1,item:'relic:crown',revision:1})).status,400);await h.action(a.token,{type:'decorate',slot:0,item:null,revision:1});await h.action(a.token,{type:'decorate',slot:0,item:'relic:crown',revision:2});assert.equal(h.records['users/a'].townHallXP,30);assert.equal(h.records['users/a'].rubyItems['relic:crown'],1);});
test('project receipts prevent double-spending and progression is private',async()=>{const h=harness(),a=(await h.join('a')).value,b=(await h.join('b')).value;h.records['users/a'].townHallXP=90;const body={type:'project',project:'stonework',actionId:'test-project-action-0001'};const first=await h.action(a.token,body);assert.equal(first.status,200);assert.equal(first.value.progress.level,2);const balance=h.records['users/a'].gems.bronze;await h.action(a.token,body);assert.equal(h.records['users/a'].gems.bronze,balance);assert.equal(h.records['users/a'].townHallXP,110);assert.equal((await h.call('state',{token:b.token})).value.progress.level,1);assert.equal((await h.action(a.token,{...body,project:'forged',actionId:'test-project-action-0002'})).status,400);});
