const test=require('node:test'),assert=require('node:assert/strict'),economy=require('./village-economy'),layout=require('./public/village-layout');
const user=()=>({townHallXP:8500,gems:{bronze:100},villageLayout:{'house:0':0}});
test('house upgrades charge separately and increase population 3, 5, 10',()=>{let u=user();assert.equal(layout.profile(u).villagers,3);u={...u,...economy.action(u,{action:'upgrade-house',house:'house:0',revision:0})};assert.equal(u.gems.bronze,75);assert.equal(layout.profile(u).villagers,5);assert.throws(()=>economy.action(u,{action:'upgrade-house',house:'house:0',revision:0}),/changed/);u={...u,...economy.action(u,{action:'upgrade-house',house:'house:0',revision:1})};assert.equal(u.gems.bronze,35);assert.equal(layout.profile(u).villagers,10);assert.throws(()=>economy.action(u,{action:'upgrade-house',house:'house:0',revision:2}),/below/);});
test('mines unlock at Town Hall 2, 4, 5, 7, 10',()=>{const xp=require('./town-hall-progress').THRESHOLDS;assert.deepEqual(xp.map(townHallXP=>economy.profile({townHallXP}).mines.filter(m=>m.unlocked).length),[0,1,1,2,3,3,4,4,4,5]);});
test('one worker per mine, exact 3-minute output, no double claims, capped one-hour shifts',()=>{let u=user(),now=1000;const start={action:'start-household',house:'house:0'};u={...u,...economy.action(u,start,now)};assert.throws(()=>economy.action(u,start,now),/already/);assert.equal(economy.profile(u,now+179999).mines[0].claimable,0);u={...u,...economy.action(u,{action:'collect-mine',mine:0},now+180000)};assert.equal(u.gems.bronze,101);assert.throws(()=>economy.action(u,{action:'collect-mine',mine:0},now+180000),/No rubies/);assert.equal(economy.profile(u,now+7200000).mines[0].claimable,19);assert.equal(economy.profile(u,now+3600000).workers.length,3);u={...u,...economy.action(u,start,now+7200000)};assert.equal(u.gems.bronze,120);assert.equal(economy.profile(u,now+7200000).mines[0].claimable,0);});
test('mine actions reject locked mines and missing residents',()=>{assert.throws(()=>economy.action({...user(),townHallXP:0},{action:'start-household',house:'house:0'}),/unlocked/);assert.throws(()=>economy.action({...user(),villageLayout:{}},{action:'start-household',house:'house:0'}),/existing/);});
test('houses cost 10, obey hall caps and preserve upgrade state when moved',()=>{let u={gems:{bronze:30}};let p=layout.profile(u).positions;assert.throws(()=>layout.validate(u,{...p,'house:0':0,'house:1':2},0,0),/Town Hall/);u={...u,...layout.validate(u,{...p,'house:0':0},0,0)};assert.equal(u.gems.bronze,20);u.villageHouseTiers['house:0']=2;u={...u,...layout.validate(u,{...u.villageLayout,'house:0':2},1,0)};assert.equal(u.gems.bronze,20);assert.equal(layout.profile(u).villagers,5);assert.throws(()=>layout.validate({gems:{bronze:9}},{...p,'house:0':0},0,0),/10 rubies/);});
test('forge adds one ruby per upgrade for two and three cards only',()=>{const recipe=require('./gem-utils').gemRecipe;for(let level=0;level<10;level++){assert.equal(recipe({name:'Bronze',sellPrice:1},3,level).reward,12+level);assert.equal(recipe({name:'Bronze',sellPrice:1},2,level).reward,7+level);assert.equal(recipe({name:'Bronze',sellPrice:1},1,level).reward,3);assert.equal(recipe({name:'Silver',sellPrice:1},3,level).reward,12);}});

test('households occupy distinct available mines and cannot work twice',()=>{let u={...user(),villageLayout:{'house:0':0,'house:1':2,'house:2':4}};for(let i=0;i<3;i++){u={...u,...economy.action(u,{action:'start-household',house:`house:${i}`},1000)};assert.equal(u.rubyMineShifts[i].house,`house:${i}`);}assert.equal(economy.profile(u,1000).workers.length,0);assert.throws(()=>economy.action(u,{action:'start-household',house:'house:0'},1000),/already/);});
test('a full mine prevents another household starting, and larger households do not multiply output',()=>{for(const tier of [1,2,3]){let u={...user(),townHallXP:100,villageLayout:{'house:0':0,'house:1':2},villageHouseTiers:{'house:0':tier}};u={...u,...economy.action(u,{action:'start-household',house:'house:0'},1000)};assert.equal(economy.profile(u,181000).mines[0].claimable,1);assert.equal(economy.profile(u,3601000).mines[0].claimable,20);assert.throws(()=>economy.action(u,{action:'start-household',house:'house:1'},1000),/available/);}});
test('legacy individual shifts remain claimable and prevent splitting that household',()=>{let u={...user(),rubyMineShifts:{0:{worker:'house:0/1',started:1000,claimed:0}}};assert.throws(()=>economy.action(u,{action:'start-household',house:'house:0'},2000),/already/);u={...u,...economy.action(u,{action:'recall-mine',mine:0},181000)};assert.equal(u.gems.bronze,101);assert.equal(economy.profile(u,181000).workers.length,3);assert.ok(economy.action(u,{action:'start-household',house:'house:0'},181000).rubyMineShifts[0].house);});
test('recall collects only unclaimed complete intervals and frees the worker immediately',()=>{let u=user();u={...u,...economy.action(u,{action:'start-household',house:'house:0'},1000)};u={...u,...economy.action(u,{action:'collect-mine',mine:0},181000)};u={...u,...economy.action(u,{action:'recall-mine',mine:0},451000)};assert.equal(u.gems.bronze,102);assert.equal(economy.profile(u,451000).workers.length,3);assert.equal(economy.profile(u,9999999).mines[0].claimable,0);assert.throws(()=>economy.action(u,{action:'recall-mine',mine:0},451000),/no villager/);assert.throws(()=>economy.action(u,{action:'collect-mine',mine:0},451000),/No rubies/);});
test('early recall pays zero, and completed-shift recall pays at most twenty',()=>{for(const [elapsed,earned] of [[0,0],[179999,0],[180000,1],[7200000,20]]){let u=user();u={...u,...economy.action(u,{action:'start-household',house:'house:0'},1000)};u={...u,...economy.action(u,{action:'recall-mine',mine:0},1000+elapsed)};assert.equal(u.gems.bronze,100+earned);assert.equal(economy.profile(u,1000+elapsed).workers.length,3);}});
