const test=require('node:test'),assert=require('node:assert/strict'),layout=require('./public/village-layout');
const setup=()=>{const u={townHallXP:100,gems:{bronze:50}};return {...u,...layout.migration(u,1)};};
const free=(u,id)=>layout.PLOTS.find(p=>layout.validPlacement(id,p.id,layout.profile(u).positions));
test('migration preserves existing placements and houses but future unlocks remain unplaced',()=>{const u={townHallXP:100,villageLayout:{'house:0':0},villageHouseTiers:{'house:0':2}},before=layout.profile(u),next={...u,...layout.migration(u,1)},p=layout.profile(next);assert.equal(p.positions['house:0'],before.positions['house:0']);assert.equal(p.houseTiers['house:0'],2);assert.equal(p.positions.farmhouse,before.positions.farmhouse);assert.equal(p.positions.petstation,undefined);next.townHallXP=300;assert.equal(layout.profile(next).positions.petstation,undefined);assert.deepEqual(layout.migration(next,2),{});});
test('circle placements charge once and reject occupied spots, invalid plots and stale saves',()=>{let u=setup();const n=free(u,'house:0').id,positions={...layout.profile(u).positions,'house:0':n};const update=layout.validate(u,positions,u.villageLayoutRevision,1);assert.equal(update.gems.bronze,40);u={...u,...update};assert.throws(()=>layout.validate(u,{...positions,'house:1':n},u.villageLayoutRevision,1),/empty circular/);assert.throws(()=>layout.validate(u,{...positions,'house:0':99999},u.villageLayoutRevision,1),/circular land/);assert.throws(()=>layout.validate(u,positions,0,1),/changed/);const moved={...positions,'house:0':free(u,'house:0').id};assert.equal(layout.validate(u,moved,u.villageLayoutRevision,1).gems,undefined);});
test('new buildings require their unlock and use circular spots',()=>{const u=setup(),positions=layout.profile(u).positions,n=free(u,'petstation').id;assert.throws(()=>layout.validate(u,{...positions,petstation:n},u.villageLayoutRevision,1),/not unlocked/);const update=layout.validate(u,{...positions,petstation:n},u.villageLayoutRevision,2);assert.equal(update.villageLayout.petstation,n);const edge=layout.PLOTS.find(p=>p.grid&&!layout.Grid.fits('petstation',p.col,p.row));assert.throws(()=>layout.validate(u,{...positions,petstation:edge.id},u.villageLayoutRevision,2),/empty circular/);const removed={...positions};delete removed.townhall;assert.throws(()=>layout.validate(u,removed,u.villageLayoutRevision,1),/must stay/);});

test('brand-new islands start with the Town Hall and keep starter buildings in the tray',()=>{const u=layout.initial();assert.deepEqual(Object.keys(layout.profile(u).positions),['townhall']);assert.throws(()=>require('./vault-job').action(u,{action:'vault-start'}),/Place/);});

test('old grid saves migrate to nearby unique circles without losing buildings or house tiers',()=>{const u={villageGridVersion:2,villageLayout:{townhall:8,'house:0':50,farmhouse:70},villageHouseTiers:{'house:0':3},villageLayoutRevision:7};const next={...u,...layout.migration(u,9)};assert.equal(next.villageLayout.townhall,8);assert.equal(Object.keys(next.villageLayout).length,3);assert.equal(new Set(Object.values(next.villageLayout)).size,3);assert.ok(Object.values(next.villageLayout).every(n=>n<layout.legacyCount));assert.equal(layout.profile(next).houseTiers['house:0'],3);assert.equal(next.villageLayoutRevision,8);assert.deepEqual(layout.migration(next,9),{});});
